INSERT INTO CardType (name)
VALUES ('Minion'),
       ('Spell'),
       ('Weapon');

INSERT INTO CardRarity (name)
VALUES ('Common'),
       ('Free'),
       ('Rare'),
       ('Epic'),
       ('Legendary');

INSERT INTO CardBack(name, description)
VALUES ('Classic', 'The only card back you''ll ever need.'),
       ('Legend', 'Wow. Hardcore. Acquired from achieving Legend Rank in Ranked Play.'),
       ('Winter Veil Wreath',
        'A beautiful Winter Veil wreath around a snow globe full of THE FROSTY DESTRUCTION OF YOUR OPPONENTS! I Mean... good cheer. Acquired from Winter Veil 2015-2017 or when available in the shop.'),
       ('Mark of Hakkar',
        'Look out! This card back''s gone viral! Acquired by encountering another player with the Mark of Hakkar card back in any play mode.');

INSERT INTO Player(username, password, fav_card_back_id, email)
VALUES ('Chester', 'b794385f2d1ef7ab4d9273d1906381b44f2f6f2588a3efb96a49188331984753', 1, 'komaroff404@gmail.com'),
       ('Forsen', '67f544ece9af8743cecd07cba03ffeada3ae43f1f6aa277ac41abea18ec491d6', 1, 'forsen@gmail.com'),
       ('Thijs', '81285d02f41c3f0d10ffae5cbb267fef28ba14c0ec528d68983e42aae8a3b1cc', 1, 'thijs@gmail.com');

BEGIN;
INSERT INTO Class(name, hero_id)
VALUES ('Druid', 1),
       ('Hunter', 2),
       ('Mage', 3),
       ('Paladin', 4),
       ('Priest', 5),
       ('Rogue', 6),
       ('Shaman', 7),
       ('Warlock', 8),
       ('Warrior', 9);

INSERT INTO Hero(name, class_id, description)
VALUES ('Malfurion Stormage', 1,
        'The lord of the night elves is a wise and noble leader. Yes, those antlers are real.'),
       ('Rexxar', 2, 'He only feels at home in the wilderness with his beasts. Super secret: Misha is his favorite.'),
       ('Jaina Proudmoore', 3,
        'The Kirin Tor''s leader is a powerful sorceress. She used to be a lot nicer before the Theramore thing.'),
       ('Uther Lightbringer', 4,
        'Leader of the Knights of the Silver Hand. Best-selling author of The Light and How to Swing It.'),
       ('Anduin Wrynn', 5, 'The future King of Stormwind is a kind, gentle soul. Except when he''s in Shadowform.'),
       ('Valeera Sanguinar', 6,
        'Expert assassin. Deadly gladiator. Best knife skills in her cooking class, according to survivors.'),
       ('Thrall', 7, 'Thrall quit his former job as Warchief to save the world and spend more time with his family.'),
       ('Gul''dan', 8, 'Talented, persuasive and hard-working. Too bad he wants to feed your soul to demons.'),
       ('Garrosh Hellscream', 9, 'This former Warchief of the Horde isn''t bitter about being deposed. Not at all.'),
       ('Lunara', 1,
        'The first daughter of Cenarius: fierce defender of nature and natural hair-care products. Obtained during the launch of the Year of the Raven'),
       ('Alleria Windrunner', 2,
        'The high elf Ranger Captain is a peerless archer. Ask any of the orcs she used for target practice.'),
       ('Medivh', 3, 'The Guardian of Titisfal is a force for good. Demonic possession is a manageable condition'),
       ('Lady Liadrin', 4,
        'Since the resoration of the Sunwell, the Blood Lnight Matriarch''s mood seems, well, sunnier! Obtained by reaching level 20 on a new character in World of Warcraft.'),
       ('Tyrande Whisperwind', 5,
        'Unlike some people, this leader didn''t fall asleep on the job. We''re looking at you, Malfurion. Obtained from a special promotion.'),
       ('Maiev Shadowsong', 6,
        'Dedicated to rooting out demonic corruption, Maiev once jailed Illidan for ten thousand years. And that was just his first offense. Obtained during the launch of the Year of the Mammoth.'),
       ('Morgle the Oracle', 7, 'Mrrgl mrrgl mrrrrrrrrgl. Mrrrrrrgl! Mrgl? Obtained by recruiting a friend.'),
       ('Nemsy Necrofizzle', 8, 'Siphoning souls with a smile! Obtained from participating in Fireside Gatherings.'),
       ('Magni Bronzebeard', 9,
        'Lord of Ironforge. King of Khaz Modan. Grand Explorer. Moira''s Dad. Huggable Leader.');
COMMIT;

INSERT INTO CollectionHero(player_id, hero_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9),
       (1, 12),
       (1, 13),
       (1, 15),
       (1, 16),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (2, 8),
       (2, 9),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (3, 6),
       (3, 7),
       (3, 8),
       (3, 9),
       (3, 10),
       (3, 11),
       (3, 12),
       (3, 13),
       (3, 14),
       (3, 15),
       (3, 16),
       (3, 17),
       (3, 18);

INSERT INTO FavoriteHero(player_id, class_id, fav_hero_id)
VALUES (1, 1, 1),
       (1, 2, 2),
       (1, 3, 12),
       (1, 4, 13),
       (1, 5, 5),
       (1, 6, 15),
       (1, 7, 16),
       (1, 8, 8),
       (1, 9, 9),
       (2, 1, 1),
       (2, 2, 2),
       (2, 3, 3),
       (2, 4, 4),
       (2, 5, 5),
       (2, 6, 6),
       (2, 7, 7),
       (2, 8, 8),
       (2, 9, 9),
       (3, 1, 10),
       (3, 2, 11),
       (3, 3, 12),
       (3, 4, 13),
       (3, 5, 14),
       (3, 6, 15),
       (3, 7, 16),
       (3, 8, 17),
       (3, 9, 18);

INSERT INTO PlayerCardBack(player_id, card_back_id)
VALUES (1, 1),
       (1, 2),
       (2, 1),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4);

INSERT INTO Deck(number, name, class_id, player_id)
VALUES (1, 'Face Hunter', 2, 1),
       (1, 'To Legend', 3, 2),
       (1, 'Blizzcon2013', 2, 3),
       (2, 'Control Warrior', 9, 3);

INSERT INTO Card(name, neutral, type, cost, rarity, elite, attack, health, description)
VALUES ('Timber Wolf', FALSE, 1, 1, 2, FALSE, 1, 1, 'Your other Beasts have +1 Attack.'),
       ('Houndmaster', FALSE, 1, 4, 2, FALSE, 4, 3, 'Battlecry: Give a friendly Beast +2/+2 and Taunt.'),
       ('Starving Buzzard', FALSE, 1, 5, 2, FALSE, 3, 2, 'Whenever you summon a Beast, draw a card.'),
       ('Tundra Rhino', FALSE, 1, 5, 2, FALSE, 2, 5, 'Your Beasts have Charge.'),
       ('Arcane Shot', FALSE, 2, 1, 2, FALSE, NULL, NULL, 'Deal 2 damage.'),
       ('Tracking', FALSE, 2, 1, 2, FALSE, NULL, NULL,
        'Look at the top 3 cards of your deck. Draw one and discard the others.'),
       ('Hunter''s Mark', FALSE, 2, 2, 2, FALSE, NULL, NULL, 'Change a minion''s Health to 1.'),
       ('Animal Companion', FALSE, 2, 3, 2, FALSE, NULL, NULL, 'Summon a random Beast Companion.'),
       ('Kill Command', FALSE, 2, 3, 2, FALSE, NULL, NULL,
        'Deal 3 damage. If you control a Beast, deal 5 damage instead.'),
       ('Multi-Shot', FALSE, 2, 4, 2, FALSE, NULL, NULL, 'Deal 3 damage to two random enemy minions.'),
       ('Water Elemental', FALSE, 1, 4, 2, FALSE, 3, 6, 'Freeze any character damaged by this minion.'),
       ('Arcane Missiles', FALSE, 2, 1, 2, FALSE, NULL, NULL, 'Deal 3 damage randomly split among all enemies.'),
       ('Mirror Image', FALSE, 2, 0, 2, FALSE, NULL, NULL, 'Summon two 0/2 minions with Taunt.'),
       ('Arcane Explosion', FALSE, 2, 2, 2, FALSE, NULL, NULL, 'Deal 1 damage to all enemy minions.'),
       ('Frostbolt', FALSE, 2, 2, 2, FALSE, NULL, NULL, 'Deal 3 damage to a character and Freeze it.'),
       ('Arcane Intellect', FALSE, 2, 3, 2, FALSE, NULL, NULL, 'Draw 2 cards.'),
       ('Frost Nova', FALSE, 2, 3, 2, FALSE, NULL, NULL, 'Freeze all enemy minions.'),
       ('Fireball', FALSE, 2, 4, 2, FALSE, NULL, NULL, 'Deal 6 damage.'),
       ('Polymorph', FALSE, 2, 4, 2, FALSE, NULL, NULL, 'Transform a minion into a 1/1 Sheep.'),
       ('Flamestrike', FALSE, 2, 7, 2, FALSE, NULL, NULL, 'Deal 4 damage to all enemy minions.'),
       ('Charge', FALSE, 2, 1, 2, FALSE, NULL, NULL,
        'Give a friendly minion Charge. It can''t attack heroes this turn.'),
       ('Whirlwind', FALSE, 2, 1, 2, FALSE, NULL, NULL, 'Deal 1 damage to ALL minions.'),
       ('Cleave', FALSE, 2, 2, 2, FALSE, NULL, NULL, 'Deal 2 damage to two random enemy minions.'),
       ('Execute', FALSE, 2, 1, 2, FALSE, NULL, NULL, 'Destroy a damaged enemy minion.'),
       ('Heroic Strike', FALSE, 2, 2, 2, FALSE, NULL, NULL, 'Give your hero +4 Attack this turn.'),
       ('Shield Block', FALSE, 2, 3, 2, FALSE, NULL, NULL, 'Gain 5 Armor. Draw a card.'),
       ('Warsong Commander', FALSE, 1, 3, 2, FALSE, 2, 3, 'Your Charge minions have +1 Attack.'),
       ('Kor''kron Elite', FALSE, 1, 4, 2, FALSE, 4, 3, 'Charge'),
       ('Fiery War Axe', FALSE, 3, 3, 2, FALSE, 3, 2, NULL),
       ('Arcanite Reaper', FALSE, 3, 5, 2, FALSE, 5, 2, NULL),
       ('Freezing Trap', FALSE, 2, 2, 1, FALSE, NULL, NULL,
        'Secret: When an enemy minion attacks, return it to its owner''s hand. It costs (2) more.'),
       ('Scavenging Hyena', FALSE, 1, 2, 1, FALSE, 2, 2, 'Whenever a friendly Beast dies, gain +2/+1.'),
       ('Eaglehorn Bow', FALSE, 3, 3, 3, FALSE, 3, 2, 'Whenever a friendly Secret is revealed, gain +1 Durability.'),
       ('Snake Trap', FALSE, 2, 2, 4, FALSE, NULL, NULL,
        'Secret: When one of your minions is attacked, summon three 1/1 Snakes.'),
       ('King Krush', FALSE, 1, 9, 5, TRUE, 8, 8, 'Charge'),
       ('Mana Wyrm', FALSE, 1, 1, 1, FALSE, 1, 3, 'Whenever you cast a spell, gain +1 Attack.'),
       ('Sorcerer''s Apprentice', FALSE, 1, 2, 1, FALSE, 3, 2, 'Your spells cost (1) less.'),
       ('Blizzard', FALSE, 2, 6, 3, FALSE, NULL, NULL, 'Deal 2 damage to all enemy minions and Freeze them.'),
       ('Pyroblast', FALSE, 2, 10, 4, FALSE, NULL, NULL, 'Deal 10 damage.'),
       ('Archmage Antonidas', FALSE, 1, 7, 5, TRUE, 5, 7,
        'Whenever you cast a spell, add a ''Fireball'' spell to your hand.'),
       ('Inner Rage', FALSE, 2, 0, 1, FALSE, NULL, NULL, 'Deal 1 damage to a minion and give it +2 Attack.'),
       ('Slam', FALSE, 2, 2, 1, FALSE, NULL, NULL, 'Deal 2 damage to a minion. If it survives, draw a card.'),
       ('Frothing Berserker', FALSE, 1, 3, 3, FALSE, 2, 4, 'Whenever a minion takes damage, gain +1 Attack.'),
       ('Brawl', FALSE, 2, 5, 4, FALSE, NULL, NULL, 'Destroy all minions except one. (chosen randomly)'),
       ('Grommash Hellscream', FALSE, 1, 8, 5, TRUE, 4, 9, 'Charge Has +6 Attack while damaged.'),
       ('Wisp', TRUE, 1, 0, 1, FALSE, 1, 1, NULL),
       ('Leper Gnome', TRUE, 1, 1, 1, FALSE, 1, 1, 'Deathrattle: Deal 2 damage to the enemy hero.'),
       ('Acidic Swamp Ooze', TRUE, 1, 2, 2, FALSE, 3, 2, 'Battlecry: Destroy your opponent''s weapon.'),
       ('Novice Engineer', TRUE, 1, 2, 2, FALSE, 1, 1, 'Battlecry: Draw a card.'),
       ('Bloodmage Thalnos', TRUE, 1, 2, 5, TRUE, 1, 1, 'Spell Damage +1 Deathrattle: Draw a card.'),
       ('Doomsayer', TRUE, 1, 2, 4, FALSE, 0, 7, 'At the start of your turn, destroy ALL minions.'),
       ('Knife Juggler', TRUE, 1, 2, 3, FALSE, 3, 2, 'After you summon a minion, deal 1 damage to a random enemy.'),
       ('Loot Hoarder', TRUE, 1, 2, 1, FALSE, 2, 1, 'Deathrattle: Draw a card.'),
       ('Lorewalker Cho', TRUE, 1, 2, 5, TRUE, 0, 4,
        'Whenever a player casts a spell, put a copy into the other player’s hand.'),
       ('Nat Pagle', TRUE, 1, 2, 5, TRUE, 0, 4,
        'At the start of your turn, you have a 50% chance to draw an extra card.'),
       ('Youthful Brewmaster', TRUE, 1, 2, 1, FALSE, 3, 2,
        'Battlecry: Return a friendly minion from the battlefield to your hand.'),
       ('Ironfur Grizzly', TRUE, 1, 2, 1, FALSE, 3, 2, NULL),
       ('Razorfen Hunter', TRUE, 1, 3, 2, FALSE, 2, 3, 'Battlecry: Summon a 1/1 Boar.'),
       ('Shattered Sun Cleric', TRUE, 1, 3, 2, FALSE, 3, 2, 'Battlecry: Give a friendly minion +1/+1.'),
       ('Silverback Patriarch', TRUE, 1, 3, 2, FALSE, 1, 4, 'Taunt'),
       ('Wolfrider', TRUE, 1, 3, 2, FALSE, 3, 1, 'Charge'),
       ('Ironbeak Owl', TRUE, 1, 2, 1, FALSE, 2, 1, 'Battlecry: Silence a minion.'),
       ('Tinkmaster Overspark', TRUE, 1, 3, 5, TRUE, 3, 3,
        'Battlecry: Transform another random minion into a 5/5 Devilsaur or a 1/1 Squirrel.'),
       ('Chillwind Yeti', TRUE, 1, 4, 2, FALSE, 4, 5, NULL),
       ('Sen''jin Shieldmasta', TRUE, 1, 4, 2, FALSE, 3, 5, 'Taunt'),
       ('Defender of Argus', TRUE, 1, 4, 3, FALSE, 2, 3, 'Battlecry: Give adjacent minions +1/+1 and Taunt.'),
       ('Big Game Hunter', TRUE, 1, 3, 4, FALSE, 4, 2, 'Battlecry: Destroy a minion with 7 or more Attack.'),
       ('Stranglethorn Tiger', TRUE, 1, 5, 1, FALSE, 5, 5, 'Stealth'),
       ('Boulderfist Ogre', TRUE, 1, 6, 2, FALSE, 6, 7, NULL),
       ('Cairne Bloodhoof', TRUE, 1, 6, 5, TRUE, 4, 5, 'Deathrattle: Summon a 4/5 Baine Bloodhoof.'),
       ('Hogger', TRUE, 1, 6, 5, TRUE, 4, 4, 'At the end of your turn, summon a 2/2 Gnoll with Taunt.'),
       ('The Black Knight', TRUE, 1, 6, 5, TRUE, 4, 5, 'Battlecry: Destroy an enemy minion with Taunt.'),
       ('Baron Geddon', TRUE, 1, 7, 5, TRUE, 7, 5, 'At the end of your turn, deal 2 damage to ALL other characters.'),
       ('Stormwind Champion', TRUE, 1, 7, 2, FALSE, 6, 6, 'Your other minions have +1/+1.'),
       ('War Golem', TRUE, 1, 7, 2, FALSE, 7, 7, NULL),
       ('Gruul', TRUE, 1, 8, 5, TRUE, 7, 7, 'At the end of each turn, gain +1/+1 .'),
       ('Alexstrasza', TRUE, 1, 9, 5, TRUE, 8, 8, 'Battlecry: Set a hero''s remaining Health to 15.'),
       ('Deathwing', TRUE, 1, 10, 5, TRUE, 12, 12, 'Battlecry: Destroy all other minions and discard your hand.'),
       ('Sunwalker', TRUE, 1, 6, 3, FALSE, 4, 5, 'Taunt Divine Shield'),
       ('Priestess of Elune', TRUE, 1, 6, 1, FALSE, 5, 4, 'Battlecry: Restore 4 Health to your hero.'),
       ('Violet Teacher', TRUE, 1, 4, 3, FALSE, 3, 5, 'Whenever you cast a spell, summon a 1/1 Violet Apprentice.'),
       ('Silvermoon Guardian', TRUE, 1, 4, 1, FALSE, 3, 3, 'Divine Shield'),
       ('Dark Iron Dwarf', TRUE, 1, 4, 1, FALSE, 4, 4, 'Battlecry: Give a minion +2 Attack this turn.'),
       ('Gnomish Inventor', TRUE, 1, 4, 2, FALSE, 2, 4, 'Battlecry: Draw a card.'),
       ('Thrallmar Farseer', TRUE, 1, 3, 1, FALSE, 2, 3, 'Windfury'),
       ('Tauren Warrior', TRUE, 1, 3, 1, FALSE, 2, 3, 'Taunt Has +3 Attack while damaged.'),
       ('Earthen Ring Farseer', TRUE, 1, 3, 1, FALSE, 3, 3, 'Battlecry: Restore 3 Health.'),
       ('Wild Pyromancer', TRUE, 1, 2, 3, FALSE, 3, 2, 'After you cast a spell, deal 1 damage to ALL minions.'),
       ('Young Dragonhawk', TRUE, 1, 1, 2, FALSE, 1, 1, 'Windfury'),
       ('Argent Squire', TRUE, 1, 1, 1, FALSE, 1, 1, NULL);


INSERT INTO CardClass(card_id, class_id)
VALUES (1, 2),
       (2, 2),
       (3, 2),
       (4, 2),
       (5, 2),
       (6, 2),
       (7, 2),
       (8, 2),
       (9, 2),
       (10, 2),
       (11, 3),
       (12, 3),
       (13, 3),
       (14, 3),
       (15, 3),
       (16, 3),
       (17, 3),
       (18, 3),
       (19, 3),
       (20, 3),
       (21, 9),
       (22, 9),
       (23, 9),
       (24, 9),
       (25, 9),
       (26, 9),
       (27, 9),
       (28, 9),
       (29, 9),
       (30, 9),
       (31, 2),
       (32, 2),
       (33, 2),
       (34, 2),
       (35, 2),
       (36, 3),
       (37, 3),
       (38, 3),
       (39, 3),
       (40, 3),
       (41, 9),
       (42, 9),
       (43, 9),
       (44, 9),
       (45, 9);


INSERT INTO CollectionCard(player_id, card_id, quantity)
VALUES (2, 1, 2),
       (2, 2, 2),
       (2, 3, 2),
       (2, 4, 2),
       (2, 5, 2),
       (2, 6, 2),
       (2, 7, 2),
       (2, 8, 2),
       (2, 9, 2),
       (2, 10, 2),
       (2, 11, 2),
       (2, 12, 2),
       (2, 13, 2),
       (2, 14, 2),
       (2, 15, 2),
       (2, 16, 2),
       (2, 17, 2),
       (2, 18, 2),
       (2, 19, 2),
       (2, 20, 2),
       (2, 21, 2),
       (2, 22, 2),
       (2, 23, 2),
       (2, 24, 2),
       (2, 25, 2),
       (2, 26, 2),
       (2, 27, 2),
       (2, 28, 2),
       (2, 29, 2),
       (2, 30, 2),
       (2, 31, 2),
       (2, 32, 2),
       (2, 33, 2),
       (2, 34, 2),
       (2, 35, 2),
       (2, 36, 2),
       (2, 37, 2),
       (2, 38, 2),
       (2, 39, 2),
       (2, 40, 2),
       (2, 41, 2),
       (2, 42, 2),
       (2, 43, 2),
       (2, 44, 2),
       (2, 45, 2),
       (3, 1, 2),
       (3, 2, 2),
       (3, 3, 2),
       (3, 4, 2),
       (3, 5, 2),
       (3, 6, 2),
       (3, 7, 2),
       (3, 8, 2),
       (3, 9, 2),
       (3, 10, 2),
       (3, 11, 2),
       (3, 12, 2),
       (3, 13, 2),
       (3, 14, 2),
       (3, 15, 2),
       (3, 16, 2),
       (3, 17, 2),
       (3, 18, 2),
       (3, 19, 2),
       (3, 20, 2),
       (3, 21, 2),
       (3, 22, 2),
       (3, 23, 2),
       (3, 24, 2),
       (3, 25, 2),
       (3, 26, 2),
       (3, 27, 2),
       (3, 28, 2),
       (3, 29, 2),
       (3, 30, 2),
       (3, 31, 2),
       (3, 32, 2),
       (3, 33, 2),
       (3, 34, 2),
       (3, 35, 2),
       (3, 36, 2),
       (3, 37, 2),
       (3, 38, 2),
       (3, 39, 2),
       (3, 40, 2),
       (3, 41, 2),
       (3, 42, 2),
       (3, 43, 2),
       (3, 44, 2),
       (3, 45, 2),
       (3, 46, 2),
       (3, 47, 2),
       (3, 48, 2),
       (3, 49, 2),
       (3, 50, 2),
       (3, 51, 2),
       (3, 52, 2),
       (3, 53, 2),
       (3, 54, 2),
       (3, 55, 2),
       (3, 56, 2),
       (3, 57, 2),
       (3, 58, 2),
       (3, 59, 2),
       (3, 60, 2),
       (3, 61, 2),
       (3, 62, 2),
       (3, 63, 2),
       (3, 64, 2),
       (3, 65, 2),
       (3, 66, 2),
       (3, 67, 2),
       (3, 68, 2),
       (3, 69, 2),
       (3, 70, 2),
       (3, 71, 2),
       (3, 72, 2),
       (3, 73, 2),
       (3, 74, 2),
       (3, 75, 2),
       (3, 76, 2),
       (3, 77, 2),
       (3, 78, 2),
       (3, 79, 2),
       (3, 80, 2),
       (3, 81, 2),
       (3, 82, 2),
       (3, 83, 2),
       (3, 84, 2),
       (3, 85, 2),
       (3, 86, 2),
       (3, 87, 2),
       (3, 88, 2),
       (3, 89, 2),
       (3, 90, 2),
       (1, 1, 1),
       (1, 2, 2),
       (1, 5, 2),
       (1, 6, 2),
       (1, 7, 1),
       (1, 8, 1),
       (1, 9, 2),
       (1, 10, 1),
       (1, 11, 2),
       (1, 17, 2),
       (1, 18, 1),
       (1, 19, 2),
       (1, 20, 1),
       (1, 21, 2),
       (1, 22, 2),
       (1, 25, 42),
       (1, 26, 2),
       (1, 27, 1),
       (1, 28, 2),
       (1, 29, 2),
       (1, 30, 1),
       (1, 31, 2),
       (1, 34, 322),
       (1, 35, 2),
       (1, 36, 2),
       (1, 37, 2),
       (1, 38, 1),
       (1, 39, 2),
       (1, 40, 1),
       (1, 41, 2),
       (1, 44, 2),
       (1, 45, 2),
       (1, 46, 1),
       (1, 47, 2),
       (1, 48, 2),
       (1, 49, 1),
       (1, 50, 2),
       (1, 54, 69),
       (1, 55, 1),
       (1, 56, 2),
       (1, 57, 1),
       (1, 58, 7),
       (1, 61, 1),
       (1, 62, 2),
       (1, 63, 1),
       (1, 65, 1),
       (1, 66, 1),
       (1, 67, 3),
       (1, 71, 2),
       (1, 72, 1),
       (1, 73, 1337),
       (1, 74, 11),
       (1, 80, 1),
       (1, 81, 228),
       (1, 82, 1),
       (1, 83, 2),
       (1, 84, 1),
       (1, 85, 2),
       (1, 86, 2),
       (1, 87, 1);

INSERT INTO CardInDeck(deck_no, player_id, card_id, amount)
VALUES (1, 1, 1, 1),
       (1, 1, 2, 2),
       (1, 1, 5, 2),
       (1, 1, 6, 2),
       (1, 1, 7, 1),
       (1, 1, 8, 1),
       (1, 1, 9, 2),
       (1, 1, 10, 1),
       (1, 1, 31, 2),
       (1, 1, 34, 2),
       (1, 1, 35, 2),
       (1, 1, 46, 1),
       (1, 1, 47, 2),
       (1, 1, 48, 2),
       (1, 1, 49, 1),
       (1, 1, 54, 2),
       (1, 1, 55, 1),
       (1, 1, 56, 2),
       (1, 1, 57, 1),

       (1, 2, 11, 2),
       (1, 2, 12, 2),
       (1, 2, 13, 2),
       (1, 2, 14, 2),
       (1, 2, 15, 2),
       (1, 2, 16, 2),
       (1, 2, 17, 2),
       (1, 2, 18, 2),
       (1, 2, 19, 2),
       (1, 2, 20, 2),
       (1, 2, 36, 2),
       (1, 2, 37, 2),
       (1, 2, 38, 2),
       (1, 2, 39, 2),
       (1, 2, 40, 2),

       (1, 3, 1, 2),
       (1, 3, 2, 2),
       (1, 3, 3, 2),
       (1, 3, 4, 2),
       (1, 3, 5, 2),
       (1, 3, 6, 2),
       (1, 3, 7, 2),
       (1, 3, 8, 2),
       (1, 3, 9, 2),
       (1, 3, 10, 2),
       (1, 3, 31, 2),
       (1, 3, 32, 2),
       (1, 3, 33, 2),
       (1, 3, 34, 2),
       (1, 3, 35, 2),

       (2, 3, 21, 2),
       (2, 3, 22, 2),
       (2, 3, 23, 2),
       (2, 3, 24, 2),
       (2, 3, 25, 2),
       (2, 3, 26, 2),
       (2, 3, 27, 2),
       (2, 3, 28, 2),
       (2, 3, 29, 2),
       (2, 3, 30, 2),
       (2, 3, 41, 2),
       (2, 3, 42, 2),
       (2, 3, 43, 2),
       (2, 3, 44, 2),
       (2, 3, 45, 2);