DROP DOMAIN IF EXISTS POSINT CASCADE;
DROP DOMAIN IF EXISTS QDECK CASCADE;
DROP DOMAIN IF EXISTS QCARD CASCADE;

DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS CardBack CASCADE;
DROP TABLE IF EXISTS PlayerCardBack CASCADE;
DROP TABLE IF EXISTS Class CASCADE;
DROP TABLE IF EXISTS Hero CASCADE;
DROP TABLE IF EXISTS FavoriteHero CASCADE;
DROP TABLE IF EXISTS CollectionHero CASCADE;
DROP TABLE IF EXISTS CardType CASCADE;
DROP TABLE IF EXISTS CardRarity CASCADE;
DROP TABLE IF EXISTS Card CASCADE;
DROP TABLE IF EXISTS CardClass CASCADE;
DROP TABLE IF EXISTS Deck CASCADE;
DROP TABLE IF EXISTS CollectionCard CASCADE;
DROP TABLE IF EXISTS CardInDeck CASCADE;